PROJECT_SOURCES = $$CPP_SOURCE_TREE/carousel
PROJECT_HEADERS = $$HPP_SOURCE_TREE/carousel

SOURCES += \
    $$PROJECT_SOURCES/booting/BootloaderBase.cpp \
    $$PROJECT_SOURCES/booting/CarouselBootloader.cpp \
    $$PROJECT_SOURCES/commands/BaseUndoableCommand.cpp \
    $$PROJECT_SOURCES/commands/EnableComponentCommand.cpp \
    $$PROJECT_SOURCES/commands/InstallComponentsCommand.cpp \
    $$PROJECT_SOURCES/componentsystem/AbsolutePathComponentLocationConstructorDelegate.cpp \
    $$PROJECT_SOURCES/componentsystem/BaseComponent.cpp \
    $$PROJECT_SOURCES/componentsystem/ComponentCollection.cpp \
    $$PROJECT_SOURCES/componentsystem/ComponentDefinition.cpp \
    $$PROJECT_SOURCES/componentsystem/ComponentDependencies.cpp \
    $$PROJECT_SOURCES/componentsystem/ComponentInstaller.cpp \
    $$PROJECT_SOURCES/componentsystem/ComponentLoader.cpp \
    $$PROJECT_SOURCES/componentsystem/ComponentManager.cpp \
    $$PROJECT_SOURCES/componentsystem/ComponentProvider.cpp \
    $$PROJECT_SOURCES/componentsystem/CompositeComponentProvider.cpp \
    $$PROJECT_SOURCES/componentsystem/DefinitionConstuctor.cpp \
    $$PROJECT_SOURCES/componentsystem/DependenciesSolvingResult.cpp \
    $$PROJECT_SOURCES/componentsystem/DependencySolver.cpp \
    $$PROJECT_SOURCES/componentsystem/DirectoryComponentProvider.cpp \
    $$PROJECT_SOURCES/componentsystem/DirectoryInstaller.cpp \
    $$PROJECT_SOURCES/componentsystem/DirectoryWatchingComponentProvider.cpp \
    $$PROJECT_SOURCES/componentsystem/FileComponentProvider.cpp \
    $$PROJECT_SOURCES/componentsystem/ParentDefinition.cpp \
    $$PROJECT_SOURCES/componentsystem/ParentDefinitions.cpp \
    $$PROJECT_SOURCES/componentsystem/ProxyComponent.cpp \
    $$PROJECT_SOURCES/componentsystem/Version.cpp \
    $$PROJECT_SOURCES/componentsystem/WebInstaller.cpp \
    $$PROJECT_SOURCES/componentsystem/XmlDefinitionParser.cpp \
    $$PROJECT_SOURCES/logging/LoggerFacade.cpp \
    $$PROJECT_SOURCES/logging/NullLogger.cpp \
    $$PROJECT_SOURCES/logging/TextLogger.cpp \
    $$PROJECT_SOURCES/utils/FileUtils.cpp \
    $$PROJECT_SOURCES/utils/ServiceLocator.cpp \

HEADERS += \
    $$PROJECT_HEADERS/booting/BootloaderBase.h \
    $$PROJECT_HEADERS/booting/CarouselBootloader.h \
    $$PROJECT_HEADERS/booting/IBootloader.h \
    $$PROJECT_HEADERS/carousel_global.h \
    $$PROJECT_HEADERS/commands/BaseUndoableCommand.h \
    $$PROJECT_HEADERS/commands/EnableComponentCommand.h \
    $$PROJECT_HEADERS/commands/InstallComponentsCommand.h \
    $$PROJECT_HEADERS/commands/IUndoableCommand.h \
    $$PROJECT_HEADERS/commands/IUndoStack.h \
    $$PROJECT_HEADERS/componentsystem/AbsolutePathComponentLocationConstructorDelegate.h \
    $$PROJECT_HEADERS/componentsystem/BaseComponent.h \
    $$PROJECT_HEADERS/componentsystem/ComponentCollection.h \
    $$PROJECT_HEADERS/componentsystem/ComponentDefinition.h \
    $$PROJECT_HEADERS/componentsystem/ComponentDependencies.h \
    $$PROJECT_HEADERS/componentsystem/ComponentExport.h \
    $$PROJECT_HEADERS/componentsystem/ComponentExport.h \
    $$PROJECT_HEADERS/componentsystem/ComponentInstaller.h \
    $$PROJECT_HEADERS/componentsystem/ComponentLoader.h \
    $$PROJECT_HEADERS/componentsystem/ComponentManager.h \
    $$PROJECT_HEADERS/componentsystem/ComponentProvider.h \
    $$PROJECT_HEADERS/componentsystem/CompositeComponentProvider.h \
    $$PROJECT_HEADERS/componentsystem/DefinitionConstuctor.h \
    $$PROJECT_HEADERS/componentsystem/DependenciesSolvingResult.h \
    $$PROJECT_HEADERS/componentsystem/DependencySolver.h \
    $$PROJECT_HEADERS/componentsystem/DirectoryComponentProvider.h \
    $$PROJECT_HEADERS/componentsystem/DirectoryInstaller.h \
    $$PROJECT_HEADERS/componentsystem/DirectoryWatchingComponentProvider.h \
    $$PROJECT_HEADERS/componentsystem/FileComponentProvider.h \
    $$PROJECT_HEADERS/componentsystem/IComponent.h \
    $$PROJECT_HEADERS/componentsystem/IComponentDependencies.h \
    $$PROJECT_HEADERS/componentsystem/IComponentExtension.h \
    $$PROJECT_HEADERS/componentsystem/IComponentInstaller.h \
    $$PROJECT_HEADERS/componentsystem/IComponentLoader.h \
    $$PROJECT_HEADERS/componentsystem/IComponentLocationConstructorDelegate.h \
    $$PROJECT_HEADERS/componentsystem/IComponentManager.h \
    $$PROJECT_HEADERS/componentsystem/IComponentProvider.h \
    $$PROJECT_HEADERS/componentsystem/IDefinitionParser.h \
    $$PROJECT_HEADERS/componentsystem/IDirectoryComponentProvider.h \
    $$PROJECT_HEADERS/componentsystem/ParentDefinition.h \
    $$PROJECT_HEADERS/componentsystem/ParentDefinitions.h \
    $$PROJECT_HEADERS/componentsystem/ProxyComponent.h \
    $$PROJECT_HEADERS/componentsystem/Version.h \
    $$PROJECT_HEADERS/componentsystem/WebInstaller.h \
    $$PROJECT_HEADERS/componentsystem/XmlDefinitionParser.h \
    $$PROJECT_HEADERS/logging/ILoggerEngine.h \
    $$PROJECT_HEADERS/logging/ILoggerEngineCreator.h \
    $$PROJECT_HEADERS/logging/LoggerFacade.h \
    $$PROJECT_HEADERS/logging/NullLogger.h \
    $$PROJECT_HEADERS/logging/TextLogger.h \
    $$PROJECT_HEADERS/utils/FileUtils.h \
    $$PROJECT_HEADERS/utils/IServiceLocator.h \
    $$PROJECT_HEADERS/utils/ListDictionary.h \
    $$PROJECT_HEADERS/utils/ObservableList.h \
    $$PROJECT_HEADERS/utils/ServiceLocator.h \
    $$PROJECT_HEADERS/utils/TypeObjectsMap.h \

